/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar.kedaibonit.view;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import tugasbesar.kedaibonit.controller.PelangganController;
import tugasbesar.kedaibonit.entity.Pelanggan;
import tugasbesar.kedaibonit.error.PelangganException;
import tugasbesar.kedaibonit.event.PelangganListener;
import tugasbesar.kedaibonit.model.PelangganModel;
import tugasbesar.kedaibonit.model.TabelPelangganModel;
import java.sql.SQLException;
import tugasbesar.kedaibonit.controller.CatatUtangController;
import tugasbesar.kedaibonit.database.KedaiBonitDatabase;
import tugasbesar.kedaibonit.entity.CatatUtang;
import tugasbesar.kedaibonit.error.CatatUtangException;
import tugasbesar.kedaibonit.event.CatatUtangListener;
import tugasbesar.kedaibonit.model.CatatUtangModel;
import tugasbesar.kedaibonit.model.TabelCatatUtangModel;
import tugasbesar.kedaibonit.service.CatatUtangDao;
import tugasbesar.kedaibonit.service.PelangganDao;

/**
 *
 * @author CarakaMR
 */
public class MainPanelView extends javax.swing.JPanel implements PelangganListener, ListSelectionListener, CatatUtangListener {

    private TabelPelangganModel tabelModel;
    private PelangganModel model;
    private PelangganController controller;
    private TabelCatatUtangModel tabelModelCU;
    private CatatUtangModel modelCU;
    private CatatUtangController controllerCU;
    
    
    public MainPanelView() {
        
        tabelModel = new TabelPelangganModel();
        
        model = new PelangganModel();
        model.setListener(this);
        
        controller = new PelangganController();
        controller.setModel(model);
        
        tabelModelCU = new TabelCatatUtangModel();
        
        modelCU = new CatatUtangModel();
        modelCU.setListener(this);
        
        controllerCU = new CatatUtangController();
        controllerCU.setModel(modelCU);
        
        initComponents();
        
        tableCatatUtang.getSelectionModel().addListSelectionListener(this);
        
        tablePelanggan.getSelectionModel().addListSelectionListener(this);
        
        tablePelanggan.setModel(tabelModel);
        
        tableCatatUtang.setModel(tabelModelCU);
    }

    

    public JTable getTableCatatUtang() {
        return tableCatatUtang;
    }

    public JTextField getTxtIDCU() {
        return txtIDCU;
    }

    public JTextField getTxtJatuhTempoCU() {
        return txtJatuhTempoCU;
    }

    public JTextField getTxtNamaCU() {
        return txtNamaCU;
    }

    public JTextField getTxtNominalCU() {
        return txtNominalCU;
    }

    public JTextField getTxtStatusBayarCU() {
        return txtStatusBayarCU;
    }

    public JTextField getTxtTglUtangCU() {
        return txtTglUtangCU;
    }
    public JTextField getTxtNamaBarangCU() {
        return txtNamaBarangCU;
    }

    
    

    public JTable getTablePelanggan() {
        return tablePelanggan;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTextField getTxtNamaPelanggan() {
        return txtNamaPelanggan;
    }

    public JTextField getTxtNoHp() {
        return txtNoHp;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnDataPelanggan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCatatUtang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnBayarUtang = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        dashboardView = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        datapelangganView = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNamaPelanggan = new javax.swing.JTextField();
        txtNoHp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePelanggan = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        catatutangView = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtIDCU = new javax.swing.JTextField();
        txtJatuhTempoCU = new javax.swing.JTextField();
        txtTglUtangCU = new javax.swing.JTextField();
        txtNamaCU = new javax.swing.JTextField();
        txtNamaBarangCU = new javax.swing.JTextField();
        txtStatusBayarCU = new javax.swing.JTextField();
        txtNominalCU = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCatatUtang = new javax.swing.JTable();
        btnResetCU = new javax.swing.JButton();
        btnSimpanCU = new javax.swing.JButton();
        btnUbahCU = new javax.swing.JButton();
        bayarutangView = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        bodyPanel.setBackground(new java.awt.Color(84, 204, 242));

        menuPanel.setBackground(new java.awt.Color(47, 128, 237));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/kedaibonit/view/online_store_120px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(239, 255, 52));
        jLabel2.setText("BONIT");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(239, 255, 52));
        jLabel3.setText("KEDAI");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/kedaibonit/view/combo_chart_80px.png"))); // NOI18N

        btnDashboard.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDashboard.setText("DASHBOARD");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/kedaibonit/view/people_80px.png"))); // NOI18N

        btnDataPelanggan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDataPelanggan.setText("DATA PELANGGAN");
        btnDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataPelangganActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/kedaibonit/view/money_80px.png"))); // NOI18N

        btnCatatUtang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCatatUtang.setText("CATAT UTANG");
        btnCatatUtang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatatUtangActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasbesar/kedaibonit/view/ticket_purchase_80px.png"))); // NOI18N

        btnBayarUtang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBayarUtang.setText("BAYAR UTANG");
        btnBayarUtang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarUtangActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(menuPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnDataPelanggan)))
                            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(menuPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnCatatUtang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(menuPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBayarUtang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(35, 35, 35))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnDashboard)))
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnDataPelanggan)))
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnCatatUtang)))
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnBayarUtang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addContainerGap())
        );

        mainPanel.setBackground(new java.awt.Color(84, 204, 242));
        mainPanel.setLayout(new java.awt.CardLayout());

        dashboardView.setBackground(new java.awt.Color(84, 204, 242));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel8.setText("DASHBOARD");

        javax.swing.GroupLayout dashboardViewLayout = new javax.swing.GroupLayout(dashboardView);
        dashboardView.setLayout(dashboardViewLayout);
        dashboardViewLayout.setHorizontalGroup(
            dashboardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardViewLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel8)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        dashboardViewLayout.setVerticalGroup(
            dashboardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(706, Short.MAX_VALUE))
        );

        mainPanel.add(dashboardView, "card2");

        datapelangganView.setBackground(new java.awt.Color(84, 204, 242));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel9.setText("DATA PELANGGAN");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("ID  :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("NAMA PELANGGAN  :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("NO HP/WA  :");

        txtId.setEditable(false);

        tablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePelanggan);

        btnReset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout datapelangganViewLayout = new javax.swing.GroupLayout(datapelangganView);
        datapelangganView.setLayout(datapelangganViewLayout);
        datapelangganViewLayout.setHorizontalGroup(
            datapelangganViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datapelangganViewLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(194, 194, 194))
            .addGroup(datapelangganViewLayout.createSequentialGroup()
                .addGroup(datapelangganViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datapelangganViewLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(datapelangganViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(datapelangganViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(datapelangganViewLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnReset)
                        .addGap(53, 53, 53)
                        .addComponent(btnSimpan)
                        .addGap(51, 51, 51)
                        .addComponent(btnUbah))
                    .addGroup(datapelangganViewLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        datapelangganViewLayout.setVerticalGroup(
            datapelangganViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datapelangganViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(83, 83, 83)
                .addGroup(datapelangganViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datapelangganViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(datapelangganViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(datapelangganViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah))
                .addGap(159, 159, 159))
        );

        mainPanel.add(datapelangganView, "card3");

        catatutangView.setBackground(new java.awt.Color(84, 204, 242));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel13.setText("CATAT UTANG");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("ID  :");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("NAMA PELANGGAN  :");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("TANGGAL BER-UTANG  :");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("NAMA BARANG  :");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("NOMINAL (Rp)  :");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("JATUH TEMPO  :");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("STATUS BAYAR  :");

        txtIDCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCUActionPerformed(evt);
            }
        });

        txtNamaCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaCUActionPerformed(evt);
            }
        });

        txtNamaBarangCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaBarangCUActionPerformed(evt);
            }
        });

        tableCatatUtang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableCatatUtang);

        btnResetCU.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnResetCU.setText("RESET");
        btnResetCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetCUActionPerformed(evt);
            }
        });

        btnSimpanCU.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSimpanCU.setText("SIMPAN");
        btnSimpanCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanCUActionPerformed(evt);
            }
        });

        btnUbahCU.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUbahCU.setText("UBAH");
        btnUbahCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahCUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout catatutangViewLayout = new javax.swing.GroupLayout(catatutangView);
        catatutangView.setLayout(catatutangViewLayout);
        catatutangViewLayout.setHorizontalGroup(
            catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catatutangViewLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(btnResetCU)
                .addGap(60, 60, 60)
                .addComponent(btnSimpanCU)
                .addGap(54, 54, 54)
                .addComponent(btnUbahCU)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catatutangViewLayout.createSequentialGroup()
                .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(catatutangViewLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel13))
                    .addGroup(catatutangViewLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(catatutangViewLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNamaCU, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(catatutangViewLayout.createSequentialGroup()
                                .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(catatutangViewLayout.createSequentialGroup()
                                        .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTglUtangCU)
                                            .addComponent(txtJatuhTempoCU, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(catatutangViewLayout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtIDCU, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(142, 142, 142)))
                                .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNamaBarangCU)
                    .addComponent(txtNominalCU)
                    .addComponent(txtStatusBayarCU, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catatutangViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        catatutangViewLayout.setVerticalGroup(
            catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catatutangViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(66, 66, 66)
                .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(txtIDCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaBarangCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNamaCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtNominalCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTglUtangCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(txtJatuhTempoCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatusBayarCU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(catatutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResetCU)
                    .addComponent(btnSimpanCU)
                    .addComponent(btnUbahCU))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        mainPanel.add(catatutangView, "card4");

        bayarutangView.setBackground(new java.awt.Color(84, 204, 242));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel14.setText("BAYAR UTANG");

        javax.swing.GroupLayout bayarutangViewLayout = new javax.swing.GroupLayout(bayarutangView);
        bayarutangView.setLayout(bayarutangViewLayout);
        bayarutangViewLayout.setHorizontalGroup(
            bayarutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bayarutangViewLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel14)
                .addContainerGap(264, Short.MAX_VALUE))
        );
        bayarutangViewLayout.setVerticalGroup(
            bayarutangViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bayarutangViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(706, Short.MAX_VALUE))
        );

        mainPanel.add(bayarutangView, "card5");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCatatUtangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatatUtangActionPerformed
         //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //add Panel
        mainPanel.add(catatutangView);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnCatatUtangActionPerformed

    private void btnBayarUtangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarUtangActionPerformed
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //add Panel
        mainPanel.add(bayarutangView);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnBayarUtangActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
       int dialogBtn = JOptionPane.YES_NO_CANCEL_OPTION;
       int dialogResult = JOptionPane.showConfirmDialog(this, "Anda Yakin Akan Keluar", "Peringatan", dialogBtn);
       
       if(dialogResult==0) {
           //true condition
           System.exit(0);
       }else{
           //false condition
       }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //add Panel
        mainPanel.add(dashboardView);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataPelangganActionPerformed
        //remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        //add Panel
        mainPanel.add(datapelangganView);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnDataPelangganActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        controller.resetPelanggan(this);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        controller.insertPelanggan(this);
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        controller.updatePelanggan(this);
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnResetCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetCUActionPerformed
        controllerCU.resetCatatUtang(this);
    }//GEN-LAST:event_btnResetCUActionPerformed

    private void btnSimpanCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanCUActionPerformed
        controllerCU.insertCatatUtang(this);
    }//GEN-LAST:event_btnSimpanCUActionPerformed

    private void btnUbahCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahCUActionPerformed
        controllerCU.updateCatatUtang(this);
    }//GEN-LAST:event_btnUbahCUActionPerformed

    private void txtNamaBarangCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaBarangCUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaBarangCUActionPerformed

    private void txtNamaCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaCUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaCUActionPerformed

    private void txtIDCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCUActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bayarutangView;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btnBayarUtang;
    private javax.swing.JButton btnCatatUtang;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDataPelanggan;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnResetCU;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpanCU;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnUbahCU;
    private javax.swing.JPanel catatutangView;
    private javax.swing.JPanel dashboardView;
    private javax.swing.JPanel datapelangganView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTable tableCatatUtang;
    private javax.swing.JTable tablePelanggan;
    private javax.swing.JTextField txtIDCU;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJatuhTempoCU;
    private javax.swing.JTextField txtNamaBarangCU;
    private javax.swing.JTextField txtNamaCU;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JTextField txtNominalCU;
    private javax.swing.JTextField txtStatusBayarCU;
    private javax.swing.JTextField txtTglUtangCU;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(PelangganModel model) {
        txtId.setText(model.getId()+"");
        txtNamaPelanggan.setText(model.getNamaPelanggan());
        txtNoHp.setText(model.getNohp());
    }

    @Override
    public void onInsert(Pelanggan pelanggan) {
        tabelModel.add(pelanggan);
    }

    @Override
    public void onUpdate(Pelanggan pelanggan) {
        int index = tablePelanggan.getSelectedRow();
        tabelModel.set(index, pelanggan);
    }

   
     @Override
    public void onChangeCU(CatatUtangModel model) {
        txtId.setText(model.getIdcu()+"");
        txtNamaCU.setText(model.getNamacu());
        txtTglUtangCU.setText(model.getTanggalBerutang());
        txtNamaBarangCU.setText(model.getNamaBarang());
        txtNominalCU.setText(model.getNominal());
        txtJatuhTempoCU.setText(model.getJatuhTempo());
        txtStatusBayarCU.setText(model.getStatusbayar());
        
    }

    @Override
    public void onInsertCU(CatatUtang catatUtang) {
        tabelModelCU.add(catatUtang);
    }

    @Override
    public void onUpdateCU(CatatUtang catatUtang) {
        int index = tableCatatUtang.getSelectedRow();
        tabelModelCU.set(index, catatUtang);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
      try {
        Pelanggan model = tabelModel.get(tablePelanggan.getSelectedRow());
        CatatUtang modelcu = tabelModelCU.get(tableCatatUtang.getSelectedRow());
        txtId.setText(model.getId()+"");
        txtNamaPelanggan.setText(model.getNamapelanggan());
        txtNoHp.setText(model.getNomorhp());
        txtIDCU.setText(modelcu.getIdCU());
        txtNamaCU.setText(modelcu.getNamacu());
        txtTglUtangCU.setText(modelcu.getTanggalBerutang());
        txtNamaBarangCU.setText(modelcu.getNamaBarang());
        txtNominalCU.setText(modelcu.getNominal());
        txtJatuhTempoCU.setText(modelcu.getJatuhTempo());
        txtStatusBayarCU.setText(modelcu.getStatusBayar());
    } catch (IndexOutOfBoundsException exception) {
    
  }
    
     
}
    
    public void loadDatabase() throws SQLException, PelangganException, CatatUtangException {
        PelangganDao dao = KedaiBonitDatabase.getPelangganDao();
        CatatUtangDao daocu = KedaiBonitDatabase.getCatatUtangDao();
        tabelModel.setList(dao.selectAllPelanggan());
        tabelModelCU.setList(daocu.selectAllUtang());
        
    }

    
   
    
}

